name: StyleFlow
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - av=8.0.2=py37h06622b3_4
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2020.12.8=h06a4308_0
  - certifi=2020.12.5=py37h06a4308_0
  - ffmpeg=4.3.1=h3215721_1
  - freetype=2.9.1=h8a8886c_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - intel-openmp=2019.4=243
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7f98852_1001
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - llvm-openmp=11.0.0=hfc4b9b4_1
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.12=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - natsort=6.0.0=py_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.6=he412f7d_0
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openh264=2.1.1=h8b12597_0
  - openssl=1.1.1i=h27cfd23_0
  - pip=19.1.1=py37_0
  - python=3.7.3=h0371630_0
  - python_abi=3.7=1_cp37m
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.22.1=py37hd81dba3_0
  - setuptools=41.0.1=py37_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.4=py37_0
  - x264=1!152.20180806=h14c3975_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.7.1
    - appdirs==1.4.4
    - astor==0.8.0
    - astunparse==1.6.3
    - attrs==19.1.0
    - backcall==0.1.0
    - bleach==3.1.0
    - cachetools==4.1.0
    - cffi==1.12.3
    - chardet==3.0.4
    - cloudpickle==1.2.1
    - cycler==0.10.0
    - cytoolz==0.9.0.1
    - dask==2.1.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - deprecated==1.2.6
    - dill==0.2.9
    - dlib==19.21.0
    - dominate==2.3.5
    - easydict==1.9
    - entrypoints==0.3
    - gast==0.2.2
    - google-auth==1.14.3
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.22.0
    - h5py==2.10.0
    - helpdev==0.6.10
    - idna==2.8
    - imageio==2.5.0
    - importlib-metadata==0.18
    - imutils==0.5.3
    - ipykernel==5.1.1
    - ipython==7.6.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.13.3
    - jinja2==2.10.1
    - jsonschema==3.0.1
    - jupyter==1.0.0
    - jupyter-client==5.2.4
    - jupyter-console==6.0.0
    - jupyter-core==4.5.0
    - keras==2.2.4
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - mako==1.1.2
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.1.0
    - mistune==0.8.4
    - nbconvert==5.5.0
    - nbformat==4.4.0
    - networkx==2.3
    - notebook==5.7.8
    - oauthlib==3.1.0
    - opencv-python==4.1.0.25
    - opt-einsum==3.2.1
    - pandocfilters==1.4.2
    - parso==0.5.0
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pillow==6.0.0
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.9
    - protobuf==3.8.0
    - psutil==5.6.3
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.19
    - pycuda==2019.1.2
    - pygments==2.4.2
    - pyparsing==2.4.0
    - pyqt5==5.13.0
    - pyqt5-sip==4.19.18
    - pyrsistent==0.14.11
    - pyside2==5.13.0
    - python-dateutil==2.8.0
    - pytools==2020.1
    - pytz==2019.1
    - pywavelets==1.0.3
    - pyyaml==5.1.1
    - pyzmq==18.0.0
    - qdarkgraystyle==1.0.2
    - qdarkstyle==2.7
    - qtconsole==4.5.1
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-image==0.15.0
    - scikit-video==1.1.11
    - scipy==1.2.1
    - send2trash==1.5.0
    - shiboken2==5.13.0
    - six==1.12.0
    - tensorboard==1.15.0
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.0
    - termcolor==1.1.0
    - terminado==0.8.2
    - testpath==0.4.2
    - toolz==0.9.0
    - torch==1.1.0
    - torchdiffeq==0.0.1
    - torchvision==0.3.0
    - tornado==6.0.3
    - tqdm==4.32.1
    - traitlets==4.3.2
    - urllib3==1.25.3
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - werkzeug==0.15.4
    - widgetsnbextension==3.4.2
    - wrapt==1.11.2
    - zipp==0.5.2

